#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Copy Dockerfile
      copy: src=Dockerfile dest=/tmp/path/

    - name: Copy Groovy Scripts
      copy: src=init.groovy.d/ dest=/tmp/path/init.groovy.d/

    - name: Build image and with build args
      docker_image:
        name: flugel-jenkins
        build:
          path: /tmp/path
        source: build

    - name: Start a container with a command
      docker_container:
        name: Jenkins
        image: flugel-jenkins
        ports:
         - "80:8080"
         - "50000:50000"
        state: started
        restart: yes

